function [x y] = m_xyCoord(t)
% This is the function that determines the coordinates of the path

% x = -t*(heaviside(t)-heaviside(t-0.5)) + ...
%     -0.5*(heaviside(t-0.5)-heaviside(t-1.5)) + ...
%     (t-2)*(heaviside(t-1.5)-heaviside(t-2.5)) + ...
%     0.5*(heaviside(t-2.5)-heaviside(t-3.5)) + ...
%     -(t-4)*(heaviside(t-3.5)-heaviside(t-4)) + ...
%     -0.5*sin(2*(t-4))*(heaviside(t-4)-heaviside(t-4-pi));
% 
% y = 0*(heaviside(t)-heaviside(t-0.5)) + ...
%     (t-0.5)*(heaviside(t-0.5)-heaviside(t-1.5)) + ...
%     1*(heaviside(t-1.5)-heaviside(t-2.5)) + ...
%     -(t-3.5)*(heaviside(t-2.5)-heaviside(t-3.5)) + ...
%     0*(heaviside(t-3.5)-heaviside(t-4)) + ...
%     -0.5*(cos(2*(t-4))-1)*(heaviside(t-4)-heaviside(t-4-pi));

x = 0*(heaviside(t)-heaviside(t-1)) + ...
    -(t-1)*(heaviside(t-1)-heaviside(t-2)) + ...
    -1*(heaviside(t-2)-heaviside(t-4)) + ...
    (t-5)*(heaviside(t-4)-heaviside(t-6)) + ...
    -(t-7)*(heaviside(t-6)-heaviside(t-7)) + ...
    (-0.5*sin(pi*(t-7)))*(heaviside(t-7)-heaviside(t-8)) + ...
    (0.5*sin(pi*(t-8)))*(heaviside(t-8)-heaviside(t-9));
    
y = t*(heaviside(t)-heaviside(t-1)) + ...
    1*(heaviside(t-1)-heaviside(t-2)) + ...
    -(t-3)*(heaviside(t-2)-heaviside(t-4)) + ...
    (t-5)*(heaviside(t-4)-heaviside(t-6)) + ...
    1*(heaviside(t-6)-heaviside(t-7)) + ...
    (0.5*cos(pi*(t-7))+0.5)*(heaviside(t-7)-heaviside(t-8)) + ...
    (0.5*cos(pi*(t-8))-0.5)*(heaviside(t-8)-heaviside(t-9)) + ...
    2*(t-9.5)*(heaviside(t-9)-heaviside(t-9.5));